apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment

spec:
  selector:
    matchLabels:
      app: my-weather-app
  replicas: 5

  template:
    metadata:
      labels:
        app: my-weather-app
    spec:
      containers:
      - name: myweatherapp
        image: myweatherapp
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
